#include "unistd.h"
#include "stdio.h"
#include "string.h"
#include "stdlib.h"

int main(int argc, char* argv[])
{
  
        
        execv("/usr/execpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheproexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheproexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheproexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheproexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheproexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheproexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheproexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheproexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotiftheprogrammreturnsminusonethanitshouldworkfineotherwisethereisamistakeexecpathsizetestusedtodeterminifthepathsizemaxerrorwilltriggercorrectlyorifnotifthepro", NULL);
        printf("ERROR - should not return\n");

   
    return 0;
}